apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  # securityContext:  
  #   fsGroup: 2000
  containers:
  - name: myapp
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - "sh"
    - "-c"
    - "sleep 1h"
    # securityContext:
    #   runAsUser: 1000
    #   runAsGroup: 3000
  nodeSelector:
    app: myapp
      
