apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: redis-storage
      mountPath: /opt/data/redis

  volumes:
  - name: redis-storage
    emptyDir: {}
