apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  hostPath:
    path: "/mnt/data"
